In [13]:
from pandas import read_excel, melt, concat
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from matplotlib import pyplot as plt
import seaborn as sb
import sys
import os
from scipy.stats import f_oneway

sys.path.append(os.path.dirname(os.path.dirname(os.getcwd())))
from helper import normality_test, equal_variance_test, independence_test, all_test

# 문제 1

유아들을 대상으로 세 가지 읽는 방법을 비교,실험하여 다음과 같은 독서평가 점수자료를 얻었다.

세 방법에 통계적으로 유의한 차이가 있는지 검정하라

In [2]:
df = read_excel('https://data.hossam.kr/E02/reading.xlsx')
df

   독서방법  점수
0     B   6
1     B   9
2     B   2
3     B  16
4     D   7
5     D   7
6     D  12
7     D  10
8     D  16
9     S  11
10    S   7
11    S   4
12    S   7
13    S   7

In [3]:
df2 = df.copy()
df2['독서방법'] = df2['독서방법'].map({'B': 1, 'D': 2, 'S': 3})
df2

    독서방법  점수
0      1   6
1      1   9
2      1   2
3      1  16
4      2   7
5      2   7
6      2  12
7      2  10
8      2  16
9      3  11
10     3   7
11     3   4
12     3   7
13     3   7

In [4]:
all_test(df2['독서방법'], df2['점수'])

d:\python\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                                 statistic   p-value  result
condition test       field
정규성       shapiro    독서방법         0.810449  0.006740   False
                     점수           0.925500  0.263591    True
          normaltest 독서방법         3.635337  0.162404    True
                     점수           1.019042  0.600783    True
          ks_2samp   독서방법 vs 점수   0.928571  0.000001   False
                     점수 vs 독서방법   0.928571  0.000001   False
등분산성      Bartlett   독서방법 vs 점수  23.394518  0.000001   False
          Fligner    독서방법 vs 점수   4.592595  0.032110   False
          Levene     독서방법 vs 점수   7.088392  0.013132   False
독립성       Chi2       독서방법 vs 점수   8.894056  0.780897    True

In [5]:
model = ols('점수 ~ C(독서방법)', data = df2).fit()
anova_lm(model)

            df      sum_sq    mean_sq         F   PR(>F)
C(독서방법)    2.0   26.464286  13.232143  0.779403  0.48244
Residual  11.0  186.750000  16.977273       NaN      NaN

#### 결과 해석
F(8, 5) = 2.657563 / p-value > 0.05 이상이므로 독서 방법에 따라 통계적으로 유의한 차이가 없다.

# 문제 2

효소 성분의 비료가 효소 함량이 증가함에 따라 토마토 모종 포기의 성장에 어떤 영향을 주는지 실험연구를 하여 다음 자료를 얻었다.

분산분석을 하여 효소 함량에 따라 토마토 모종 성장에 차이가 나는지 검정하라.

In [6]:
ef = read_excel('https://data.hossam.kr/E02/tomato.xlsx')
ef

     효소함량  모종성장
0       0  10.8
1       0   9.1
2       0  13.5
3       0   9.2
4    1000  11.1
5    1000  11.2
6    1000   8.2
7    1000  11.3
8    5000   5.4
9    5000   4.6
10   5000   7.4
11   5000   5.0
12  10000   5.8
13  10000   5.3
14  10000   3.2
15  10000   7.5

In [7]:
all_test(ef['효소함량'], ef['모종성장'])

d:\python\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                                      statistic       p-value  result
condition test       field
정규성       shapiro    효소함량              0.801869  2.883953e-03   False
                     모종성장              0.954987  5.725466e-01    True
          normaltest 효소함량              3.983248  1.364736e-01    True
                     모종성장              1.370910  5.038608e-01    True
          ks_2samp   효소함량 vs 모종성장      0.750000  1.196512e-04   False
                     모종성장 vs 효소함량      0.750000  1.196512e-04   False
등분산성      Bartlett   효소함량 vs 모종성장    189.295508  4.530102e-43   False
          Fligner    효소함량 vs 모종성장     21.384043  3.758867e-06   False
          Levene     효소함량 vs 모종성장     43.173221  2.863331e-07   False
독립성       Chi2       효소함량 vs 모종성장  21395.722772  0.000000e+00   False

In [8]:
ef['효소함량'] = ef['효소함량'].astype('category')
ef.dtypes

효소함량    category
모종성장     float64
dtype: object

In [9]:
model = ols('모종성장 ~ C(효소함량)', data = ef).fit()
anova_lm(model)

            df    sum_sq    mean_sq          F    PR(>F)
C(효소함량)    3.0  101.1275  33.709167  12.085748  0.000615
Residual  12.0   33.4700   2.789167        NaN       NaN

#### 결과 해석

f()

# 문제 3

두 가지 교육방법을 비교하기 위하여 능력이 비슷한 고등학교 학생 22명을 추출하고, 11명씩 두 집단으로 나누어 한 학기 동안 각각의 교육방법으로 교육시킨 후 치른 학기말 시험 성적이 다음과 같다.

이 자료를 이용하여 두 가지 교육방법에 대한 국어와 영어의 효과가 서로 다르다고 할 수 있는지 검정하라. (분석 목적에 맞는 데이터 재배치 과정이 필요합니다.)

In [10]:
ff = read_excel('https://data.hossam.kr/E02/edu.xlsx')
ff

    교육방법  국어  영어
0      1  65  82
1      1  87  79
2      1  73  85
3      1  79  60
4      1  81  65
5      1  69  70
6      1  55  79
7      1  76  80
8      1  77  76
9      1  70  90
10     1  88  68
11     2  75  72
12     2  69  75
13     2  83  93
14     2  81  85
15     2  72  60
16     2  79  65
17     2  85  88
18     2  89  92
19     2  90  83
20     2  77  93
21     2  95  78

In [11]:
all_test(ff['교육방법'], ff['국어'], ff['영어'])

                                       statistic       p-value  result
condition test       field
정규성       shapiro    교육방법               0.640223  3.715844e-06   False
                     국어                 0.982805  9.540115e-01    True
                     영어                 0.953426  3.686618e-01    True
          normaltest 교육방법              69.448535  8.306963e-16   False
                     국어                 1.164455  5.586526e-01    True
                     영어                 1.589026  4.518012e-01    True
          ks_2samp   교육방법 vs 국어         1.000000  9.505256e-13   False
                     국어 vs 영어           0.136364  9.900572e-01    True
                     영어 vs 교육방법         1.000000  9.505256e-13   False
등분산성      Bartlett   교육방법 vs 국어 vs 영어  96.847076  9.330922e-22   False
          Fligner    교육방법 vs 국어 vs 영어  28.806449  5.555961e-07   False
          Levene     교육방법 vs 국어 vs 영어  17.292189  1.032162e-06   False
독립성       Chi2       교육방법 vs 국어 vs 영어  27.310564  9.612377e-01    True

In [ ]:
df1 = df.filter(['교육방법', '국어'])

In [12]:
model = ols(' ~ C(국어) * C(영어)', data = df).fit()
anova_lm(model)

PatsyError: Error evaluating factor: NameError: name '교육방법' is not defined
    교육방법 ~ C(국어) * C(영어)
    ^^^^